### ISSUE TITLE
Multipos switch, how use with MCP?

### ISSUE THREAD

**Issue by lancer2000** [Gadroc/dcs-bios-arduino-mcp#1]
Hi
How to write code to use multiPos switch? 
I try this, but doesnt work:

Mcp23017 inputPins(B0100001);
const byte weaponsModePins[5] = {inputPins.getPin(1),inputPins.getPin(2), inputPins.getPin(3), inputPins.getPin(4), inputPins.getPin(5)};
SwitchMultiPos weaponsMode("WEAPONS_MODE", weaponsModePins, 5);

I get error:
cannot convert 'InputPin' to 'const byte {aka const unsigned char}' in initialization

**Comment by lancer2000** [comment]
I have in code this

Mcp23017 inputPins(B0100000); 
Switch2Pos weaponsAutoTurnBtn("WEAPONS_AUTO_TURN_BTN", inputPins.getPin(0));
Switch2Pos weaponsForwardHemiTargetBtn("WEAPONS_FORWARD_HEMI_TARGET_BTN", inputPins.getPin(1));
Switch2Pos weaponsGroundTargetBtn("WEAPONS_GROUND_TARGET_BTN", inputPins.getPin(2));

Everything is working, but if I add to code this:

const byte weaponsModePins[5] = {5,6, 7, 8, 9};
SwitchMultiPos weaponsMode("WEAPONS_MODE",weaponsModePins, 5);

compiled OK, but not working in game, even Switch2Pos

then

**Comment by Gadroc** [comment]
There are two constructors for each switch type...  One that takes pin numbers (bytes) these are for use when using pins directly attached to the arduino.  In your first post you define the const array as bytes which in the second example is turning pins 5, 6, 7, 8 and 9 on the arduino to read pins and polling them.

You need to declare the array of InputPins.  Unfortunately it looks like that is far to convoluted using the MCP code as it's setup.   I'll look at refactoring it here in the next few days.

**Comment by Gadroc** [comment]
I have refactored the library to make this easier.  Please see the new examples.
